const WORDS = [
  // Level 1 - Basic
  {id:1,word:"abandon",pos:"v",definition:"to leave completely and finally",example:"They had to abandon the sinking ship.",korean:"버리다, 포기하다",level:1},
  {id:2,word:"ability",pos:"n",definition:"the skill or power to do something",example:"She has the ability to learn quickly.",korean:"능력, 재능",level:1},
  {id:3,word:"accept",pos:"v",definition:"to take or receive something offered",example:"Please accept my sincere apology.",korean:"받아들이다, 수락하다",level:1},
  {id:4,word:"achieve",pos:"v",definition:"to successfully reach a goal",example:"She worked hard to achieve her dream.",korean:"달성하다, 성취하다",level:1},
  {id:5,word:"action",pos:"n",definition:"the process of doing something",example:"We need to take action immediately.",korean:"행동, 행위",level:1},
  {id:6,word:"admit",pos:"v",definition:"to confess or acknowledge something",example:"He finally admitted his mistake.",korean:"인정하다, 자백하다",level:1},
  {id:7,word:"affect",pos:"v",definition:"to have an influence on something",example:"The weather can affect your mood.",korean:"영향을 미치다",level:1},
  {id:8,word:"agree",pos:"v",definition:"to have the same opinion as someone",example:"I completely agree with you.",korean:"동의하다",level:1},
  {id:9,word:"allow",pos:"v",definition:"to let someone do something",example:"My parents allow me to stay up late.",korean:"허용하다, 허락하다",level:1},
  {id:10,word:"appear",pos:"v",definition:"to come into sight; to seem",example:"A rainbow appeared after the rain.",korean:"나타나다, ~처럼 보이다",level:1},
  {id:11,word:"apply",pos:"v",definition:"to make a formal request; to put into use",example:"She decided to apply for the job.",korean:"적용하다, 신청하다",level:1},
  {id:12,word:"argue",pos:"v",definition:"to give reasons for or against something",example:"They always argue about money.",korean:"주장하다, 논쟁하다",level:1},
  {id:13,word:"assume",pos:"v",definition:"to suppose something without proof",example:"Don't assume you know everything.",korean:"가정하다, 추측하다",level:1},
  {id:14,word:"avoid",pos:"v",definition:"to stay away from something or someone",example:"Try to avoid junk food.",korean:"피하다, 회피하다",level:1},
  {id:15,word:"basic",pos:"adj",definition:"forming an essential part; fundamental",example:"Water is a basic human need.",korean:"기본적인, 기초적인",level:1},
  {id:16,word:"become",pos:"v",definition:"to start to be something",example:"She wants to become a doctor.",korean:"~이 되다",level:1},
  {id:17,word:"believe",pos:"v",definition:"to think something is true",example:"I believe you can do it.",korean:"믿다",level:1},
  {id:18,word:"benefit",pos:"n",definition:"an advantage or positive effect",example:"Exercise has many health benefits.",korean:"혜택, 이익",level:1},
  {id:19,word:"brave",pos:"adj",definition:"ready to face danger without fear",example:"The brave firefighter saved the child.",korean:"용감한",level:1},
  {id:20,word:"break",pos:"v",definition:"to separate into pieces by force",example:"Be careful not to break the glass.",korean:"부수다, 깨다",level:1},
  {id:21,word:"build",pos:"v",definition:"to construct by putting parts together",example:"They plan to build a new school.",korean:"짓다, 건설하다",level:1},
  {id:22,word:"calm",pos:"adj",definition:"not showing excitement or strong emotion",example:"Stay calm during an emergency.",korean:"차분한, 평온한",level:1},
  {id:23,word:"careful",pos:"adj",definition:"giving serious attention to avoid problems",example:"Be careful when crossing the road.",korean:"조심스러운, 신중한",level:1},
  {id:24,word:"cause",pos:"n",definition:"the reason something happens",example:"Pollution is a major cause of climate change.",korean:"원인, 이유",level:1},
  {id:25,word:"change",pos:"v",definition:"to make or become different",example:"Things can change very quickly.",korean:"변화, 변하다",level:1},
  {id:26,word:"choose",pos:"v",definition:"to decide which thing you want",example:"You can choose any flavor you like.",korean:"선택하다, 고르다",level:1},
  {id:27,word:"clear",pos:"adj",definition:"easy to see, understand, or hear",example:"The instructions were very clear.",korean:"명확한, 분명한",level:1},
  {id:28,word:"collect",pos:"v",definition:"to gather things together",example:"She collects stamps as a hobby.",korean:"수집하다, 모으다",level:1},
  {id:29,word:"complete",pos:"v",definition:"to finish doing something",example:"Please complete this form by Friday.",korean:"완료하다, 완성하다",level:1},
  {id:30,word:"concern",pos:"n",definition:"a feeling of worry about something",example:"His health is a major concern.",korean:"걱정, 관심사",level:1},
  {id:31,word:"connect",pos:"v",definition:"to join or link two things together",example:"The bridge connects the two cities.",korean:"연결하다",level:1},
  {id:32,word:"consider",pos:"v",definition:"to think carefully about something",example:"Consider all options before deciding.",korean:"고려하다, 생각하다",level:1},
  {id:33,word:"continue",pos:"v",definition:"to keep happening without stopping",example:"The rain continued for three days.",korean:"계속하다",level:1},
  {id:34,word:"control",pos:"v",definition:"to have power over something",example:"You can control your own destiny.",korean:"제어하다, 통제하다",level:1},
  {id:35,word:"create",pos:"v",definition:"to make something new",example:"Artists create beautiful works of art.",korean:"창조하다, 만들다",level:1},
  {id:36,word:"decide",pos:"v",definition:"to choose after thinking about options",example:"It's hard to decide what to eat.",korean:"결정하다",level:1},
  {id:37,word:"define",pos:"v",definition:"to explain the meaning of something",example:"Can you define this word for me?",korean:"정의하다",level:1},
  {id:38,word:"depend",pos:"v",definition:"to rely on someone or something",example:"Success depends on hard work.",korean:"의존하다, 달려있다",level:1},
  {id:39,word:"describe",pos:"v",definition:"to say what something is like",example:"Describe what you saw last night.",korean:"묘사하다, 설명하다",level:1},
  {id:40,word:"develop",pos:"v",definition:"to grow or cause to grow gradually",example:"She is developing her writing skills.",korean:"발전하다, 개발하다",level:1},
  {id:41,word:"discover",pos:"v",definition:"to find something for the first time",example:"Scientists discover new species every year.",korean:"발견하다",level:1},
  {id:42,word:"discuss",pos:"v",definition:"to talk about something in detail",example:"Let's discuss the plan tomorrow.",korean:"토론하다, 논의하다",level:1},
  {id:43,word:"earn",pos:"v",definition:"to receive money in return for work",example:"She earns a good salary.",korean:"벌다, 획득하다",level:1},
  {id:44,word:"enjoy",pos:"v",definition:"to get pleasure from something",example:"I enjoy reading books at night.",korean:"즐기다",level:1},
  {id:45,word:"escape",pos:"v",definition:"to get free from a place",example:"The bird escaped from its cage.",korean:"탈출하다, 도망치다",level:1},
  {id:46,word:"examine",pos:"v",definition:"to look at something very carefully",example:"The doctor examined the patient.",korean:"조사하다, 검사하다",level:1},
  {id:47,word:"expect",pos:"v",definition:"to think something will happen",example:"I expect to hear good news soon.",korean:"기대하다, 예상하다",level:1},
  {id:48,word:"experience",pos:"n",definition:"knowledge gained by doing things",example:"She has ten years of teaching experience.",korean:"경험",level:1},
  {id:49,word:"explain",pos:"v",definition:"to make something clear and easy to understand",example:"Please explain how this works.",korean:"설명하다",level:1},
  {id:50,word:"express",pos:"v",definition:"to show thoughts or feelings in words",example:"It's important to express your feelings.",korean:"표현하다",level:1},
  {id:51,word:"fail",pos:"v",definition:"to not succeed in doing something",example:"Don't be afraid to fail; learn from it.",korean:"실패하다",level:1},
  {id:52,word:"fair",pos:"adj",definition:"treating people equally and rightly",example:"The judge made a fair decision.",korean:"공정한",level:1},
  {id:53,word:"famous",pos:"adj",definition:"known and recognized by many people",example:"She is famous for her paintings.",korean:"유명한",level:1},
  {id:54,word:"fear",pos:"n",definition:"an unpleasant feeling caused by danger",example:"She overcame her fear of heights.",korean:"두려움, 공포",level:1},
  {id:55,word:"follow",pos:"v",definition:"to come or go after someone",example:"Follow the instructions carefully.",korean:"따르다, 따라가다",level:1},
  {id:56,word:"forget",pos:"v",definition:"to fail to remember something",example:"Don't forget to lock the door.",korean:"잊다, 잊어버리다",level:1},
  {id:57,word:"freedom",pos:"n",definition:"the power to act or speak without restraint",example:"Freedom of speech is a human right.",korean:"자유",level:1},
  {id:58,word:"gather",pos:"v",definition:"to collect or bring things together",example:"People gathered in the town square.",korean:"모이다, 모으다",level:1},
  {id:59,word:"goal",pos:"n",definition:"something you are trying to achieve",example:"My goal is to speak three languages.",korean:"목표",level:1},
  {id:60,word:"grow",pos:"v",definition:"to increase in size, number, or strength",example:"The company has grown rapidly.",korean:"성장하다, 자라다",level:1},
  {id:61,word:"happen",pos:"v",definition:"to take place, especially unexpectedly",example:"Strange things happen sometimes.",korean:"발생하다, 일어나다",level:1},
  {id:62,word:"honest",pos:"adj",definition:"telling the truth and not lying",example:"Always be honest with your friends.",korean:"정직한",level:1},
  {id:63,word:"hope",pos:"n",definition:"a feeling that something good will happen",example:"Never lose hope, even in hard times.",korean:"희망",level:1},
  {id:64,word:"imagine",pos:"v",definition:"to form a picture in your mind",example:"Imagine a world without pollution.",korean:"상상하다",level:1},
  {id:65,word:"improve",pos:"v",definition:"to make something better",example:"Practice will improve your skills.",korean:"개선하다, 향상시키다",level:1},
  {id:66,word:"include",pos:"v",definition:"to have as part of a whole",example:"The price includes breakfast.",korean:"포함하다",level:1},
  {id:67,word:"increase",pos:"v",definition:"to become or make larger in amount",example:"Exercise can increase your energy.",korean:"증가하다, 늘리다",level:1},
  {id:68,word:"inspire",pos:"v",definition:"to encourage and make someone want to do something",example:"Her courage inspired many people.",korean:"영감을 주다, 고무하다",level:1},
  {id:69,word:"join",pos:"v",definition:"to become a member of a group",example:"Would you like to join our club?",korean:"참여하다, 합류하다",level:1},
  {id:70,word:"judge",pos:"v",definition:"to form an opinion about something",example:"Don't judge a book by its cover.",korean:"판단하다",level:1},
  {id:71,word:"keep",pos:"v",definition:"to continue to have or hold something",example:"Keep your promises to others.",korean:"유지하다, 지키다",level:1},
  {id:72,word:"lack",pos:"v",definition:"to not have enough of something",example:"The team lacks experience.",korean:"부족하다",level:1},
  {id:73,word:"learn",pos:"v",definition:"to gain knowledge or skill",example:"You can learn a lot from failure.",korean:"배우다, 익히다",level:1},
  {id:74,word:"limit",pos:"n",definition:"the greatest amount or extent allowed",example:"There is no limit to what you can achieve.",korean:"한계, 제한",level:1},
  {id:75,word:"manage",pos:"v",definition:"to be in charge of; to handle",example:"She manages a team of 20 people.",korean:"관리하다, 처리하다",level:1},
  {id:76,word:"mention",pos:"v",definition:"to refer to something briefly",example:"Did she mention the meeting time?",korean:"언급하다",level:1},
  {id:77,word:"move",pos:"v",definition:"to change position; to affect emotionally",example:"The speech moved the audience to tears.",korean:"움직이다, 이동하다",level:1},
  {id:78,word:"need",pos:"v",definition:"to require something",example:"Plants need sunlight to grow.",korean:"필요하다",level:1},
  {id:79,word:"offer",pos:"v",definition:"to present something for acceptance",example:"He offered to help carry the bags.",korean:"제공하다, 제안하다",level:1},
  {id:80,word:"plan",pos:"n",definition:"a detailed proposal for doing something",example:"We need a plan before we start.",korean:"계획",level:1},
  {id:81,word:"prevent",pos:"v",definition:"to stop something from happening",example:"Vaccines can prevent many diseases.",korean:"예방하다, 막다",level:1},
  {id:82,word:"protect",pos:"v",definition:"to keep someone or something safe",example:"We must protect the environment.",korean:"보호하다",level:1},
  {id:83,word:"reach",pos:"v",definition:"to arrive at a place; to achieve",example:"She reached the top of the mountain.",korean:"도달하다, 닿다",level:1},
  {id:84,word:"realize",pos:"v",definition:"to become aware of something",example:"I didn't realize how late it was.",korean:"깨닫다, 실현하다",level:1},
  {id:85,word:"reduce",pos:"v",definition:"to make something smaller in size",example:"Try to reduce your screen time.",korean:"줄이다, 감소시키다",level:1},
  {id:86,word:"remember",pos:"v",definition:"to keep in mind; to recall",example:"Remember to drink enough water.",korean:"기억하다",level:1},
  {id:87,word:"result",pos:"n",definition:"something that happens because of an action",example:"Hard work brings good results.",korean:"결과",level:1},
  {id:88,word:"share",pos:"v",definition:"to give part of something to others",example:"Share your knowledge with others.",korean:"나누다, 공유하다",level:1},
  {id:89,word:"simple",pos:"adj",definition:"easy to understand; not complicated",example:"The solution was surprisingly simple.",korean:"단순한, 간단한",level:1},
  {id:90,word:"solve",pos:"v",definition:"to find an answer to a problem",example:"Can you solve this puzzle?",korean:"해결하다, 풀다",level:1},
  {id:91,word:"support",pos:"v",definition:"to give help or encouragement",example:"My family always supports my decisions.",korean:"지지하다, 지원하다",level:1},
  {id:92,word:"try",pos:"v",definition:"to make an effort to do something",example:"Always try your best.",korean:"시도하다, 노력하다",level:1},
  {id:93,word:"understand",pos:"v",definition:"to know the meaning of something",example:"Do you understand the instructions?",korean:"이해하다",level:1},
  {id:94,word:"value",pos:"n",definition:"the importance or worth of something",example:"Education has great value in our society.",korean:"가치",level:1},
  {id:95,word:"wonder",pos:"v",definition:"to think about something with curiosity",example:"I wonder what will happen next.",korean:"궁금해하다",level:1},
  {id:96,word:"work",pos:"v",definition:"to do a job; to function properly",example:"This plan could really work.",korean:"일하다, 작동하다",level:1},
  {id:97,word:"worry",pos:"v",definition:"to feel anxious about something",example:"Don't worry, everything will be fine.",korean:"걱정하다",level:1},
  {id:98,word:"trust",pos:"v",definition:"to believe someone is honest and reliable",example:"Trust takes time to build.",korean:"신뢰하다",level:1},
  {id:99,word:"spend",pos:"v",definition:"to use time or money on something",example:"I spend two hours studying every day.",korean:"쓰다, 보내다",level:1},
  {id:100,word:"exist",pos:"v",definition:"to be real or present",example:"Happiness exists in small moments.",korean:"존재하다",level:1},

  // Level 2 - Intermediate
  {id:101,word:"absorb",pos:"v",definition:"to take in and make part of an existing whole",example:"The sponge absorbs water quickly.",korean:"흡수하다",level:2},
  {id:102,word:"acknowledge",pos:"v",definition:"to accept that something is true",example:"He acknowledged his mistake publicly.",korean:"인정하다, 인식하다",level:2},
  {id:103,word:"acquire",pos:"v",definition:"to get something, usually through effort",example:"She acquired a new language in one year.",korean:"습득하다, 획득하다",level:2},
  {id:104,word:"adapt",pos:"v",definition:"to change to suit a new situation",example:"Animals adapt to their environment.",korean:"적응하다, 조정하다",level:2},
  {id:105,word:"adequate",pos:"adj",definition:"enough for a particular purpose",example:"Make sure you get adequate sleep.",korean:"적절한, 충분한",level:2},
  {id:106,word:"advocate",pos:"v",definition:"to publicly support a cause or policy",example:"She advocates for children's rights.",korean:"옹호하다, 지지하다",level:2},
  {id:107,word:"aggressive",pos:"adj",definition:"behaving in a very determined, forceful way",example:"His aggressive approach won the deal.",korean:"공격적인, 적극적인",level:2},
  {id:108,word:"alternative",pos:"n",definition:"one of two or more available possibilities",example:"We need to find an alternative solution.",korean:"대안, 대체안",level:2},
  {id:109,word:"ambiguous",pos:"adj",definition:"having more than one possible meaning",example:"His statement was ambiguous and confusing.",korean:"모호한, 불분명한",level:2},
  {id:110,word:"analyze",pos:"v",definition:"to examine something in detail",example:"We need to analyze the data carefully.",korean:"분석하다",level:2},
  {id:111,word:"anticipate",pos:"v",definition:"to expect or predict something",example:"We did not anticipate this problem.",korean:"예상하다, 기대하다",level:2},
  {id:112,word:"appropriate",pos:"adj",definition:"suitable for a particular person or situation",example:"Wear appropriate clothing for the weather.",korean:"적절한, 알맞은",level:2},
  {id:113,word:"assess",pos:"v",definition:"to evaluate or judge the value of something",example:"Teachers assess student progress regularly.",korean:"평가하다, 측정하다",level:2},
  {id:114,word:"assist",pos:"v",definition:"to help someone do something",example:"Can you assist me with this report?",korean:"돕다, 보조하다",level:2},
  {id:115,word:"authority",pos:"n",definition:"the power to make decisions or give orders",example:"The manager has authority over the team.",korean:"권위, 권한",level:2},
  {id:116,word:"circumstance",pos:"n",definition:"a fact or condition connected with an event",example:"Success depends on your circumstances.",korean:"상황, 환경",level:2},
  {id:117,word:"classify",pos:"v",definition:"to arrange in groups based on shared qualities",example:"Scientists classify animals by species.",korean:"분류하다",level:2},
  {id:118,word:"colleague",pos:"n",definition:"a person you work with",example:"My colleague helped me finish the project.",korean:"동료",level:2},
  {id:119,word:"comprehend",pos:"v",definition:"to understand something fully",example:"It's hard to comprehend his theory.",korean:"이해하다",level:2},
  {id:120,word:"concentrate",pos:"v",definition:"to focus all attention on something",example:"I need silence to concentrate.",korean:"집중하다",level:2},
  {id:121,word:"confident",pos:"adj",definition:"feeling sure about your own abilities",example:"She gave a confident presentation.",korean:"자신감 있는",level:2},
  {id:122,word:"consequence",pos:"n",definition:"a result or effect of an action",example:"Think about the consequences of your actions.",korean:"결과, 영향",level:2},
  {id:123,word:"consistent",pos:"adj",definition:"always behaving or performing in the same way",example:"Consistent effort leads to success.",korean:"일관된, 한결같은",level:2},
  {id:124,word:"contribute",pos:"v",definition:"to give something to help achieve a goal",example:"Everyone should contribute to the team.",korean:"기여하다, 공헌하다",level:2},
  {id:125,word:"controversial",pos:"adj",definition:"causing a lot of disagreement or argument",example:"The new law is highly controversial.",korean:"논란이 많은",level:2},
  {id:126,word:"convince",pos:"v",definition:"to make someone believe something is true",example:"He convinced me to try the new dish.",korean:"설득하다",level:2},
  {id:127,word:"cooperate",pos:"v",definition:"to work together toward a common goal",example:"We must cooperate to solve this problem.",korean:"협력하다",level:2},
  {id:128,word:"critical",pos:"adj",definition:"expressing disapproval; very important",example:"Critical thinking is an essential skill.",korean:"비판적인, 중요한",level:2},
  {id:129,word:"deadline",pos:"n",definition:"the latest time by which something must be done",example:"Submit your work before the deadline.",korean:"마감일",level:2},
  {id:130,word:"debate",pos:"n",definition:"a formal discussion about a topic",example:"There was a debate about the new policy.",korean:"토론, 논쟁",level:2},
  {id:131,word:"dedicate",pos:"v",definition:"to devote time and effort to something",example:"She dedicated her life to helping others.",korean:"헌신하다, 전념하다",level:2},
  {id:132,word:"delay",pos:"v",definition:"to make something happen later than planned",example:"Bad weather delayed the flight.",korean:"지연하다, 늦추다",level:2},
  {id:133,word:"demonstrate",pos:"v",definition:"to show clearly by giving proof",example:"Let me demonstrate how to use this tool.",korean:"보여주다, 증명하다",level:2},
  {id:134,word:"distribute",pos:"v",definition:"to give something out to several people",example:"Food was distributed to the refugees.",korean:"배포하다, 나누다",level:2},
  {id:135,word:"diverse",pos:"adj",definition:"showing a great deal of variety",example:"Our city has a diverse population.",korean:"다양한",level:2},
  {id:136,word:"dominate",pos:"v",definition:"to have control or power over others",example:"One team dominated the entire game.",korean:"지배하다",level:2},
  {id:137,word:"efficient",pos:"adj",definition:"achieving maximum productivity with minimal waste",example:"An efficient worker gets more done.",korean:"효율적인",level:2},
  {id:138,word:"eliminate",pos:"v",definition:"to completely remove or get rid of",example:"We need to eliminate waste in production.",korean:"제거하다, 없애다",level:2},
  {id:139,word:"emphasize",pos:"v",definition:"to give special importance to something",example:"The teacher emphasized the importance of reading.",korean:"강조하다",level:2},
  {id:140,word:"encounter",pos:"v",definition:"to unexpectedly meet or face something",example:"We encountered many problems along the way.",korean:"마주치다, 만나다",level:2},
  {id:141,word:"enforce",pos:"v",definition:"to make sure a law or rule is obeyed",example:"Police enforce traffic laws.",korean:"시행하다, 집행하다",level:2},
  {id:142,word:"evaluate",pos:"v",definition:"to form an opinion of the value of something",example:"We need to evaluate the results carefully.",korean:"평가하다",level:2},
  {id:143,word:"evident",pos:"adj",definition:"clearly seen or understood",example:"It was evident that she was upset.",korean:"명백한, 분명한",level:2},
  {id:144,word:"expose",pos:"v",definition:"to uncover and make visible",example:"The article exposed corruption in the city.",korean:"드러내다, 노출하다",level:2},
  {id:145,word:"extensive",pos:"adj",definition:"covering a large area; thorough",example:"She has extensive knowledge of history.",korean:"광범위한, 폭넓은",level:2},
  {id:146,word:"facilitate",pos:"v",definition:"to make a process easier",example:"Technology facilitates communication.",korean:"촉진하다, 용이하게 하다",level:2},
  {id:147,word:"flexible",pos:"adj",definition:"willing and able to change; not rigid",example:"A flexible schedule helps work-life balance.",korean:"유연한, 탄력적인",level:2},
  {id:148,word:"fundamental",pos:"adj",definition:"forming a necessary base; essential",example:"Respect is fundamental to any relationship.",korean:"근본적인, 기본적인",level:2},
  {id:149,word:"generate",pos:"v",definition:"to produce or create something",example:"Solar panels generate electricity.",korean:"생성하다, 만들다",level:2},
  {id:150,word:"identify",pos:"v",definition:"to recognize and name someone or something",example:"Can you identify the main problem?",korean:"확인하다, 파악하다",level:2},
  {id:151,word:"illustrate",pos:"v",definition:"to explain or make clear using examples",example:"Let me illustrate my point with a story.",korean:"설명하다, 보여주다",level:2},
  {id:152,word:"implement",pos:"v",definition:"to put a plan or decision into action",example:"We will implement the new strategy next month.",korean:"실행하다, 이행하다",level:2},
  {id:153,word:"indicate",pos:"v",definition:"to show or point to something",example:"The data indicates a positive trend.",korean:"나타내다, 가리키다",level:2},
  {id:154,word:"influence",pos:"n",definition:"the power to affect someone or something",example:"Music has a strong influence on emotions.",korean:"영향, 영향력",level:2},
  {id:155,word:"investigate",pos:"v",definition:"to examine something carefully to find the truth",example:"Police are investigating the incident.",korean:"조사하다, 수사하다",level:2},
  {id:156,word:"justify",pos:"v",definition:"to show or prove something is right",example:"How can you justify this decision?",korean:"정당화하다",level:2},
  {id:157,word:"maintain",pos:"v",definition:"to keep something in its current state",example:"It's important to maintain good health.",korean:"유지하다",level:2},
  {id:158,word:"minimize",pos:"v",definition:"to reduce something to the smallest possible amount",example:"Try to minimize unnecessary spending.",korean:"최소화하다",level:2},
  {id:159,word:"motivate",pos:"v",definition:"to give someone a reason to do something",example:"A good leader motivates their team.",korean:"동기를 부여하다",level:2},
  {id:160,word:"negotiate",pos:"v",definition:"to discuss something to reach an agreement",example:"They negotiated a better contract.",korean:"협상하다",level:2},
  {id:161,word:"obtain",pos:"v",definition:"to get something, especially with effort",example:"She obtained her medical license.",korean:"획득하다, 얻다",level:2},
  {id:162,word:"participate",pos:"v",definition:"to be involved in an activity",example:"Everyone is encouraged to participate.",korean:"참여하다",level:2},
  {id:163,word:"perceive",pos:"v",definition:"to become aware of something through the senses",example:"How you perceive the world matters.",korean:"인식하다, 지각하다",level:2},
  {id:164,word:"preserve",pos:"v",definition:"to maintain something in its original state",example:"We must preserve our natural heritage.",korean:"보존하다, 지키다",level:2},
  {id:165,word:"priority",pos:"n",definition:"something dealt with before other things",example:"Health should be your top priority.",korean:"우선순위",level:2},
  {id:166,word:"promote",pos:"v",definition:"to support or encourage something",example:"The campaign promotes healthy eating.",korean:"촉진하다, 홍보하다",level:2},
  {id:167,word:"propose",pos:"v",definition:"to put forward a plan or idea",example:"I propose we meet every Monday.",korean:"제안하다",level:2},
  {id:168,word:"pursue",pos:"v",definition:"to follow and try to achieve something",example:"Always pursue your dreams.",korean:"추구하다",level:2},
  {id:169,word:"recognize",pos:"v",definition:"to know who someone is; to acknowledge",example:"I didn't recognize you with your new haircut.",korean:"인식하다, 알아보다",level:2},
  {id:170,word:"relevant",pos:"adj",definition:"related to the subject being considered",example:"Please provide only relevant information.",korean:"관련된, 적절한",level:2},
  {id:171,word:"resolve",pos:"v",definition:"to find a solution to a problem",example:"We need to resolve this conflict.",korean:"해결하다, 결심하다",level:2},
  {id:172,word:"restrict",pos:"v",definition:"to limit or control the size of something",example:"Access to the building is restricted.",korean:"제한하다",level:2},
  {id:173,word:"reveal",pos:"v",definition:"to make something known or visible",example:"The investigation revealed the truth.",korean:"드러내다, 공개하다",level:2},
  {id:174,word:"significant",pos:"adj",definition:"important enough to have an effect",example:"There was a significant improvement in sales.",korean:"중요한, 의미 있는",level:2},
  {id:175,word:"strategy",pos:"n",definition:"a plan to achieve a goal",example:"We need a new marketing strategy.",korean:"전략",level:2},
  {id:176,word:"sufficient",pos:"adj",definition:"enough for a particular purpose",example:"Make sure you have sufficient funds.",korean:"충분한",level:2},
  {id:177,word:"summarize",pos:"v",definition:"to briefly state the main points of something",example:"Please summarize the report in one page.",korean:"요약하다",level:2},
  {id:178,word:"sustain",pos:"v",definition:"to keep something going over time",example:"She sustained her effort throughout the year.",korean:"지속하다, 지탱하다",level:2},
  {id:179,word:"transform",pos:"v",definition:"to change completely in form or appearance",example:"The city has transformed in the last decade.",korean:"변환하다, 변형하다",level:2},
  {id:180,word:"transition",pos:"n",definition:"the process of changing from one state to another",example:"The transition to remote work was smooth.",korean:"전환, 이행",level:2},
  {id:181,word:"tremendous",pos:"adj",definition:"very great in amount, scale, or intensity",example:"She made a tremendous effort.",korean:"엄청난, 막대한",level:2},
  {id:182,word:"utilize",pos:"v",definition:"to make practical use of something",example:"We can utilize technology to improve life.",korean:"활용하다, 이용하다",level:2},
  {id:183,word:"valid",pos:"adj",definition:"based on truth; legally or officially acceptable",example:"Your argument is valid and well-reasoned.",korean:"유효한, 타당한",level:2},
  {id:184,word:"verify",pos:"v",definition:"to confirm that something is true or accurate",example:"Please verify your email address.",korean:"확인하다, 검증하다",level:2},
  {id:185,word:"visible",pos:"adj",definition:"able to be seen; noticeable",example:"Stars are visible on a clear night.",korean:"보이는, 가시적인",level:2},
  {id:186,word:"widespread",pos:"adj",definition:"distributed or occurring over a large area",example:"There is widespread support for the proposal.",korean:"광범위한, 만연한",level:2},
  {id:187,word:"withdraw",pos:"v",definition:"to remove or take away something",example:"He withdrew money from the ATM.",korean:"철수하다, 인출하다",level:2},
  {id:188,word:"witness",pos:"v",definition:"to see an event happen",example:"She witnessed the accident from her window.",korean:"목격하다",level:2},
  {id:189,word:"accomplish",pos:"v",definition:"to succeed in doing something difficult",example:"You can accomplish anything you set your mind to.",korean:"달성하다, 완수하다",level:2},
  {id:190,word:"challenge",pos:"n",definition:"something difficult that requires effort",example:"Every challenge is an opportunity to grow.",korean:"도전, 어려움",level:2},
  {id:191,word:"commitment",pos:"n",definition:"the state of being dedicated to a cause",example:"Success requires total commitment.",korean:"헌신, 약속",level:2},
  {id:192,word:"complex",pos:"adj",definition:"consisting of many connected parts",example:"The human brain is very complex.",korean:"복잡한",level:2},
  {id:193,word:"concentrate",pos:"v",definition:"to direct attention or effort on something",example:"Focus and concentrate on the task.",korean:"집중하다",level:2},
  {id:194,word:"crucial",pos:"adj",definition:"extremely important; decisive",example:"This is a crucial moment in history.",korean:"매우 중요한, 결정적인",level:2},
  {id:195,word:"current",pos:"adj",definition:"happening or existing now",example:"What is the current situation?",korean:"현재의, 최근의",level:2},
  {id:196,word:"decline",pos:"v",definition:"to decrease; to politely refuse",example:"Sales have declined this quarter.",korean:"감소하다, 거절하다",level:2},
  {id:197,word:"estimate",pos:"v",definition:"to roughly calculate the value of something",example:"Can you estimate how long this will take?",korean:"추정하다, 견적하다",level:2},
  {id:198,word:"expand",pos:"v",definition:"to increase in size, number, or scope",example:"The company plans to expand overseas.",korean:"확장하다, 확대하다",level:2},
  {id:199,word:"formal",pos:"adj",definition:"done in an official or serious way",example:"Please write a formal letter of application.",korean:"공식적인, 격식 있는",level:2},
  {id:200,word:"global",pos:"adj",definition:"relating to the whole world",example:"Climate change is a global problem.",korean:"전 세계적인, 글로벌한",level:2},

  // Level 3 - Advanced
  {id:201,word:"alleviate",pos:"v",definition:"to make pain or a problem less severe",example:"This medicine will alleviate your headache.",korean:"완화하다, 경감하다",level:3},
  {id:202,word:"altruistic",pos:"adj",definition:"showing concern for others with no personal gain",example:"Her altruistic nature made her beloved.",korean:"이타적인",level:3},
  {id:203,word:"ambivalent",pos:"adj",definition:"having mixed feelings about something",example:"I feel ambivalent about leaving my hometown.",korean:"양가적인, 상반된 감정의",level:3},
  {id:204,word:"antagonize",pos:"v",definition:"to cause someone to become hostile",example:"Don't antagonize your coworkers.",korean:"적대시하다, 반감을 사다",level:3},
  {id:205,word:"apprehensive",pos:"adj",definition:"anxious or fearful about something that may happen",example:"She was apprehensive about the surgery.",korean:"걱정스러운, 불안한",level:3},
  {id:206,word:"arbitrary",pos:"adj",definition:"based on random choice rather than reason",example:"The rules seemed arbitrary and unfair.",korean:"임의적인, 독단적인",level:3},
  {id:207,word:"articulate",pos:"adj",definition:"able to express thoughts clearly and fluently",example:"He is an articulate and persuasive speaker.",korean:"명확하게 표현하는, 유창한",level:3},
  {id:208,word:"ascertain",pos:"v",definition:"to find out something for certain",example:"We need to ascertain the facts first.",korean:"확인하다, 파악하다",level:3},
  {id:209,word:"astute",pos:"adj",definition:"having good insight and judgment",example:"She made an astute business decision.",korean:"예리한, 영리한",level:3},
  {id:210,word:"audacious",pos:"adj",definition:"willing to take surprisingly bold risks",example:"It was an audacious plan, but it worked.",korean:"대담한, 뻔뻔한",level:3},
  {id:211,word:"austere",pos:"adj",definition:"severe in manner; simple and plain",example:"The monk lived an austere life.",korean:"엄격한, 검소한",level:3},
  {id:212,word:"banal",pos:"adj",definition:"lacking originality; predictably boring",example:"The speech was filled with banal clichés.",korean:"진부한, 평범한",level:3},
  {id:213,word:"benevolent",pos:"adj",definition:"well-meaning and kindly",example:"The benevolent donor funded a new library.",korean:"자비로운, 인자한",level:3},
  {id:214,word:"brevity",pos:"n",definition:"concise and exact use of words",example:"Brevity is the soul of wit.",korean:"간결함, 짧음",level:3},
  {id:215,word:"candid",pos:"adj",definition:"truthful and straightforward",example:"I appreciate your candid feedback.",korean:"솔직한, 꾸밈없는",level:3},
  {id:216,word:"catalyst",pos:"n",definition:"a person or thing that causes a change",example:"Her speech was a catalyst for reform.",korean:"촉매, 계기",level:3},
  {id:217,word:"caustic",pos:"adj",definition:"sarcastic in a sharp and bitter way",example:"His caustic comments hurt her feelings.",korean:"신랄한, 가시 돋친",level:3},
  {id:218,word:"circumspect",pos:"adj",definition:"careful to consider all circumstances",example:"Be circumspect when making financial decisions.",korean:"신중한, 조심스러운",level:3},
  {id:219,word:"clandestine",pos:"adj",definition:"kept secret or done secretively",example:"They held clandestine meetings at night.",korean:"비밀스러운, 은밀한",level:3},
  {id:220,word:"coerce",pos:"v",definition:"to persuade someone using force or threats",example:"No one should be coerced into signing a contract.",korean:"강요하다, 강제하다",level:3},
  {id:221,word:"cogent",pos:"adj",definition:"clear, logical, and convincing",example:"She presented a cogent argument.",korean:"설득력 있는, 타당한",level:3},
  {id:222,word:"complacent",pos:"adj",definition:"too satisfied with yourself; not trying to improve",example:"Don't become complacent after early success.",korean:"자기만족적인",level:3},
  {id:223,word:"concise",pos:"adj",definition:"giving information clearly in few words",example:"A good essay should be concise.",korean:"간결한, 명료한",level:3},
  {id:224,word:"condone",pos:"v",definition:"to accept behavior that is wrong",example:"We cannot condone any form of violence.",korean:"묵인하다, 용납하다",level:3},
  {id:225,word:"conjecture",pos:"n",definition:"an opinion formed without proof",example:"His theory is based on conjecture.",korean:"추측, 추정",level:3},
  {id:226,word:"contemplate",pos:"v",definition:"to think deeply about something",example:"She sat quietly to contemplate her future.",korean:"숙고하다, 명상하다",level:3},
  {id:227,word:"contentious",pos:"adj",definition:"causing or likely to cause argument",example:"Immigration is a contentious political issue.",korean:"논쟁적인, 반목하는",level:3},
  {id:228,word:"covert",pos:"adj",definition:"not openly acknowledged; secret",example:"The spy conducted a covert operation.",korean:"은밀한, 비밀의",level:3},
  {id:229,word:"credible",pos:"adj",definition:"able to be believed; trustworthy",example:"We need a credible witness.",korean:"믿을 만한, 신뢰할 수 있는",level:3},
  {id:230,word:"cryptic",pos:"adj",definition:"having a meaning that is mysterious or obscure",example:"She left a cryptic message on his desk.",korean:"불가사의한, 수수께끼 같은",level:3},
  {id:231,word:"deceptive",pos:"adj",definition:"giving an impression different from reality",example:"Appearances can be deceptive.",korean:"기만적인, 오해를 일으키는",level:3},
  {id:232,word:"deliberate",pos:"adj",definition:"done intentionally; fully considered",example:"His deliberate pause created tension.",korean:"의도적인, 신중한",level:3},
  {id:233,word:"denounce",pos:"v",definition:"to publicly criticize or condemn",example:"The leader denounced the act of corruption.",korean:"비난하다, 고발하다",level:3},
  {id:234,word:"deplete",pos:"v",definition:"to reduce something to a very low level",example:"Fossil fuels are rapidly being depleted.",korean:"고갈시키다, 소진하다",level:3},
  {id:235,word:"desolate",pos:"adj",definition:"empty and without signs of life",example:"The ghost town was completely desolate.",korean:"황폐한, 쓸쓸한",level:3},
  {id:236,word:"detrimental",pos:"adj",definition:"tending to cause harm",example:"Smoking is detrimental to your health.",korean:"해로운, 불리한",level:3},
  {id:237,word:"diligent",pos:"adj",definition:"having or showing care in one's work",example:"A diligent student always prepares well.",korean:"근면한, 성실한",level:3},
  {id:238,word:"discern",pos:"v",definition:"to recognize or understand something",example:"It's hard to discern truth from fiction.",korean:"분별하다, 식별하다",level:3},
  {id:239,word:"disparate",pos:"adj",definition:"essentially different in kind",example:"The group had disparate backgrounds.",korean:"이질적인, 판이한",level:3},
  {id:240,word:"eloquent",pos:"adj",definition:"fluent or persuasive in speech or writing",example:"The president gave an eloquent speech.",korean:"웅변의, 유창한",level:3},
  {id:241,word:"elusive",pos:"adj",definition:"difficult to find, define, or achieve",example:"Happiness can be elusive.",korean:"파악하기 어려운",level:3},
  {id:242,word:"eminent",pos:"adj",definition:"respected and well known in a field",example:"She is an eminent scientist.",korean:"저명한, 탁월한",level:3},
  {id:243,word:"empirical",pos:"adj",definition:"based on observation and experiment",example:"The study used empirical evidence.",korean:"경험적인, 실증적인",level:3},
  {id:244,word:"ephemeral",pos:"adj",definition:"lasting for a very short time",example:"Fame can be ephemeral.",korean:"일시적인, 단명하는",level:3},
  {id:245,word:"eradicate",pos:"v",definition:"to destroy something completely",example:"The goal is to eradicate poverty.",korean:"근절하다, 완전히 없애다",level:3},
  {id:246,word:"exacerbate",pos:"v",definition:"to make a problem worse",example:"Stress can exacerbate health problems.",korean:"악화시키다",level:3},
  {id:247,word:"exemplary",pos:"adj",definition:"representing the best of its kind",example:"She received an award for exemplary service.",korean:"모범적인, 훌륭한",level:3},
  {id:248,word:"exorbitant",pos:"adj",definition:"unreasonably high in price",example:"The hotel charged an exorbitant fee.",korean:"터무니없이 비싼",level:3},
  {id:249,word:"fervent",pos:"adj",definition:"having or displaying passionate intensity",example:"She is a fervent believer in justice.",korean:"열렬한, 열정적인",level:3},
  {id:250,word:"formidable",pos:"adj",definition:"inspiring fear or respect through being powerful",example:"She was a formidable opponent.",korean:"강력한, 어마어마한",level:3},
  {id:251,word:"frugal",pos:"adj",definition:"sparing or economical with money",example:"Living frugally helps you save money.",korean:"검소한, 절약하는",level:3},
  {id:252,word:"futile",pos:"adj",definition:"producing no useful result; pointless",example:"It was futile to argue with him.",korean:"헛된, 소용없는",level:3},
  {id:253,word:"gregarious",pos:"adj",definition:"fond of company; sociable",example:"She is a gregarious and outgoing person.",korean:"사교적인",level:3},
  {id:254,word:"hypocritical",pos:"adj",definition:"claiming virtues you don't actually possess",example:"It's hypocritical to preach and not practice.",korean:"위선적인",level:3},
  {id:255,word:"impeccable",pos:"adj",definition:"in accordance with the highest standards",example:"She has impeccable taste in fashion.",korean:"흠잡을 데 없는, 완벽한",level:3},
  {id:256,word:"inevitable",pos:"adj",definition:"certain to happen; unavoidable",example:"Change is inevitable.",korean:"불가피한, 피할 수 없는",level:3},
  {id:257,word:"innate",pos:"adj",definition:"inborn; natural from birth",example:"She has an innate talent for music.",korean:"타고난, 선천적인",level:3},
  {id:258,word:"insidious",pos:"adj",definition:"proceeding harmfully in a subtle way",example:"The insidious disease spread slowly.",korean:"음험한, 서서히 해로운",level:3},
  {id:259,word:"intrepid",pos:"adj",definition:"fearless and adventurous",example:"The intrepid explorer ventured into the jungle.",korean:"용감한, 두려움 없는",level:3},
  {id:260,word:"lethargic",pos:"adj",definition:"sluggish and lacking energy",example:"He felt lethargic after a poor night's sleep.",korean:"무기력한, 나른한",level:3},
  {id:261,word:"lucid",pos:"adj",definition:"expressed clearly; easy to understand",example:"Her explanation was lucid and precise.",korean:"명확한, 명쾌한",level:3},
  {id:262,word:"malicious",pos:"adj",definition:"intending to do harm",example:"The malicious rumor ruined her reputation.",korean:"악의적인",level:3},
  {id:263,word:"meticulous",pos:"adj",definition:"showing great attention to detail",example:"She is meticulous in her research.",korean:"꼼꼼한, 세심한",level:3},
  {id:264,word:"mundane",pos:"adj",definition:"lacking interest; ordinary",example:"Even mundane tasks deserve full attention.",korean:"평범한, 세속적인",level:3},
  {id:265,word:"nonchalant",pos:"adj",definition:"appearing casually unconcerned",example:"He seemed nonchalant about failing the exam.",korean:"무관심한, 냉담한",level:3},
  {id:266,word:"ominous",pos:"adj",definition:"giving the impression something bad will happen",example:"Dark clouds looked ominous.",korean:"불길한, 험악한",level:3},
  {id:267,word:"ostracize",pos:"v",definition:"to exclude someone from society or a group",example:"He was ostracized for his unusual views.",korean:"배척하다, 추방하다",level:3},
  {id:268,word:"paradox",pos:"n",definition:"a seemingly absurd yet possibly true statement",example:"It's a paradox that the more you learn, the more you realize you don't know.",korean:"역설, 모순",level:3},
  {id:269,word:"pragmatic",pos:"adj",definition:"dealing with things sensibly and practically",example:"Take a pragmatic approach to problem-solving.",korean:"실용적인",level:3},
  {id:270,word:"profound",pos:"adj",definition:"very great or intense; having deep insight",example:"The book had a profound impact on me.",korean:"심오한, 깊은",level:3},
  {id:271,word:"prolific",pos:"adj",definition:"producing many works or results",example:"She is a prolific author with 50 books.",korean:"다작하는, 풍부한",level:3},
  {id:272,word:"rectify",pos:"v",definition:"to put something right; to correct",example:"We must rectify this error immediately.",korean:"바로잡다, 수정하다",level:3},
  {id:273,word:"relentless",pos:"adj",definition:"never stopping; determined",example:"Her relentless determination led to success.",korean:"끈질긴, 가차없는",level:3},
  {id:274,word:"resilient",pos:"adj",definition:"able to recover quickly from difficulties",example:"Children are often very resilient.",korean:"회복력 있는, 탄력적인",level:3},
  {id:275,word:"reticent",pos:"adj",definition:"not revealing one's thoughts readily",example:"He was reticent about his personal life.",korean:"말수가 적은, 내성적인",level:3},
  {id:276,word:"scrutinize",pos:"v",definition:"to examine or inspect closely",example:"The committee scrutinized every detail.",korean:"면밀히 조사하다",level:3},
  {id:277,word:"serendipity",pos:"n",definition:"the occurrence of events by chance in a happy way",example:"Meeting her was pure serendipity.",korean:"뜻밖의 행운, 우연한 발견",level:3},
  {id:278,word:"sophisticated",pos:"adj",definition:"having refined knowledge; complex",example:"The system uses sophisticated algorithms.",korean:"세련된, 정교한",level:3},
  {id:279,word:"stoic",pos:"adj",definition:"enduring pain without showing feelings",example:"She remained stoic throughout the crisis.",korean:"금욕적인, 감정을 드러내지 않는",level:3},
  {id:280,word:"tenacious",pos:"adj",definition:"holding firmly to a position; persistent",example:"His tenacious spirit helped him overcome obstacles.",korean:"끈질긴, 완강한",level:3},
  {id:281,word:"transient",pos:"adj",definition:"lasting only for a short time",example:"Fame is transient; character is forever.",korean:"일시적인, 덧없는",level:3},
  {id:282,word:"ubiquitous",pos:"adj",definition:"present, appearing everywhere",example:"Smartphones have become ubiquitous.",korean:"어디에나 있는",level:3},
  {id:283,word:"venerate",pos:"v",definition:"to regard with great respect",example:"She is venerated as a hero.",korean:"숭배하다, 경외하다",level:3},
  {id:284,word:"volatile",pos:"adj",definition:"liable to change rapidly and unpredictably",example:"The stock market is highly volatile.",korean:"불안정한, 변덕스러운",level:3},
  {id:285,word:"zealous",pos:"adj",definition:"having great energy or enthusiasm",example:"She is a zealous supporter of the cause.",korean:"열렬한, 열성적인",level:3},
  {id:286,word:"aberrant",pos:"adj",definition:"departing from an accepted standard",example:"His aberrant behavior alarmed his family.",korean:"비정상적인, 일탈하는",level:3},
  {id:287,word:"abhor",pos:"v",definition:"to regard with disgust and hatred",example:"I abhor any form of cruelty.",korean:"혐오하다, 몹시 싫어하다",level:3},
  {id:288,word:"ameliorate",pos:"v",definition:"to make something bad better",example:"New policies aim to ameliorate poverty.",korean:"개선하다, 향상시키다",level:3},
  {id:289,word:"capitulate",pos:"v",definition:"to cease to resist; to give in",example:"He finally capitulated to their demands.",korean:"굴복하다, 항복하다",level:3},
  {id:290,word:"corroborate",pos:"v",definition:"to confirm or give support to something",example:"The evidence corroborates her story.",korean:"확인하다, 뒷받침하다",level:3},
  {id:291,word:"deferential",pos:"adj",definition:"showing respect and submission to another",example:"He was deferential toward his elders.",korean:"공손한, 경의를 표하는",level:3},
  {id:292,word:"exuberant",pos:"adj",definition:"filled with lively energy and excitement",example:"The children were exuberant at the party.",korean:"활기찬, 넘치는",level:3},
  {id:293,word:"haphazard",pos:"adj",definition:"lacking any obvious principle of organization",example:"The files were arranged in a haphazard way.",korean:"무계획적인, 되는 대로의",level:3},
  {id:294,word:"impertinent",pos:"adj",definition:"not showing proper respect; rude",example:"It was impertinent of him to interrupt.",korean:"무례한, 버릇없는",level:3},
  {id:295,word:"irrevocable",pos:"adj",definition:"not able to be changed or reversed",example:"The decision was irrevocable.",korean:"돌이킬 수 없는",level:3},
  {id:296,word:"peremptory",pos:"adj",definition:"insisting on immediate obedience; abrupt",example:"She gave a peremptory command.",korean:"단호한, 독단적인",level:3},
  {id:297,word:"precipitate",pos:"v",definition:"to cause something to happen suddenly",example:"The scandal precipitated his resignation.",korean:"촉발하다, 성급히 하다",level:3},
  {id:298,word:"spurious",pos:"adj",definition:"not being what it claims to be; false",example:"He made several spurious claims.",korean:"가짜의, 허위의",level:3},
  {id:299,word:"vacillate",pos:"v",definition:"to waver between different opinions",example:"She vacillated between two job offers.",korean:"망설이다, 동요하다",level:3},
  {id:300,word:"grandiose",pos:"adj",definition:"impressive and ambitious, often excessively so",example:"He had grandiose plans that never succeeded.",korean:"웅장한, 과대한",level:3}
];
