const WORDS=[
// Level 1 - Core Business
{id:1,word:"agenda",pos:"n",definition:"a list of topics to be discussed at a meeting",example:"Please review the agenda before the meeting.",korean:"의제, 안건",level:1},
{id:2,word:"allocate",pos:"v",definition:"to distribute resources for a specific purpose",example:"We need to allocate more budget to marketing.",korean:"배분하다, 할당하다",level:1},
{id:3,word:"approve",pos:"v",definition:"to officially agree to or accept something",example:"The manager must approve all travel expenses.",korean:"승인하다",level:1},
{id:4,word:"asset",pos:"n",definition:"a valuable resource owned by a company",example:"Our brand is our most valuable asset.",korean:"자산",level:1},
{id:5,word:"audit",pos:"n",definition:"an official inspection of a company's financial accounts",example:"The company must undergo an annual audit.",korean:"감사, 회계감사",level:1},
{id:6,word:"benchmark",pos:"n",definition:"a standard point of reference for comparison",example:"We use this benchmark to measure our performance.",korean:"기준, 벤치마크",level:1},
{id:7,word:"boost",pos:"v",definition:"to increase or improve something significantly",example:"We need to boost our sales figures this quarter.",korean:"높이다, 끌어올리다",level:1},
{id:8,word:"brief",pos:"v",definition:"to give someone key information before a task",example:"Please brief the team on the new project goals.",korean:"브리핑하다, 간략히 설명하다",level:1},
{id:9,word:"budget",pos:"n",definition:"the amount of money set aside for a purpose",example:"We must stay within the budget.",korean:"예산",level:1},
{id:10,word:"clarify",pos:"v",definition:"to make something easier to understand",example:"Could you clarify the scope of this project?",korean:"명확히 하다",level:1},
{id:11,word:"client",pos:"n",definition:"a person or company that uses professional services",example:"The client needs the report by Friday.",korean:"고객, 의뢰인",level:1},
{id:12,word:"collaborate",pos:"v",definition:"to work jointly with others toward a shared goal",example:"We will collaborate with the design team on this.",korean:"협업하다",level:1},
{id:13,word:"commit",pos:"v",definition:"to dedicate oneself fully to something",example:"Are you willing to commit to this new deadline?",korean:"전념하다, 약속하다",level:1},
{id:14,word:"comply",pos:"v",definition:"to act in accordance with rules or instructions",example:"All employees must comply with the new policy.",korean:"준수하다, 따르다",level:1},
{id:15,word:"confirm",pos:"v",definition:"to state or show that something is definite",example:"Please confirm your attendance by email.",korean:"확인하다",level:1},
{id:16,word:"consult",pos:"v",definition:"to seek information or advice from an expert",example:"We should consult a lawyer before signing.",korean:"자문 구하다, 상담하다",level:1},
{id:17,word:"contract",pos:"n",definition:"a written legal agreement between two parties",example:"Both parties must sign the contract.",korean:"계약, 계약서",level:1},
{id:18,word:"coordinate",pos:"v",definition:"to organize activities so they work effectively together",example:"She will coordinate all project timelines.",korean:"조율하다, 조정하다",level:1},
{id:19,word:"deadline",pos:"n",definition:"the latest time by which work must be completed",example:"We cannot extend the deadline any further.",korean:"마감일",level:1},
{id:20,word:"delegate",pos:"v",definition:"to entrust a task or responsibility to another person",example:"A good manager knows how to delegate effectively.",korean:"위임하다",level:1},
{id:21,word:"deliver",pos:"v",definition:"to provide something as promised or required",example:"We are expected to deliver results by Q3.",korean:"납품하다, 결과를 내다",level:1},
{id:22,word:"demand",pos:"n",definition:"the desire of buyers to purchase goods or services",example:"Customer demand for this product is increasing.",korean:"수요, 요구",level:1},
{id:23,word:"discuss",pos:"v",definition:"to talk about something in detail with others",example:"Let us discuss this at tomorrow's meeting.",korean:"논의하다",level:1},
{id:24,word:"document",pos:"v",definition:"to record information officially in writing",example:"Please document all changes to the process.",korean:"문서화하다",level:1},
{id:25,word:"draft",pos:"v",definition:"to prepare a written version of something for review",example:"I will draft a response to the client today.",korean:"초안을 작성하다",level:1},
{id:26,word:"efficient",pos:"adj",definition:"achieving results with minimum waste of resources",example:"We need a more efficient approval workflow.",korean:"효율적인",level:1},
{id:27,word:"engage",pos:"v",definition:"to involve or attract someone's participation",example:"We need to engage more customers online.",korean:"참여시키다, 끌어들이다",level:1},
{id:28,word:"evaluate",pos:"v",definition:"to carefully assess the quality or value of something",example:"We will evaluate each proposal next week.",korean:"평가하다",level:1},
{id:29,word:"expand",pos:"v",definition:"to become or make larger in size or scope",example:"We plan to expand into three new markets.",korean:"확장하다",level:1},
{id:30,word:"expense",pos:"n",definition:"money spent on something; a cost incurred",example:"Submit your expense report by the end of the month.",korean:"비용, 지출",level:1},
{id:31,word:"feedback",pos:"n",definition:"information given in response to a product or performance",example:"We always welcome constructive feedback.",korean:"피드백",level:1},
{id:32,word:"flexible",pos:"adj",definition:"willing and able to adapt to new circumstances",example:"Our team has a flexible work arrangement.",korean:"유연한",level:1},
{id:33,word:"forecast",pos:"n",definition:"a prediction of future trends or financial performance",example:"The quarterly forecast looks very promising.",korean:"예측, 전망",level:1},
{id:34,word:"goal",pos:"n",definition:"a desired outcome that an individual or team works toward",example:"Define a clear goal for each project phase.",korean:"목표",level:1},
{id:35,word:"growth",pos:"n",definition:"an increase in size, value, or importance",example:"We are targeting ten percent growth this year.",korean:"성장",level:1},
{id:36,word:"hire",pos:"v",definition:"to employ someone for a job",example:"We plan to hire five engineers this quarter.",korean:"채용하다",level:1},
{id:37,word:"implement",pos:"v",definition:"to put a decision or plan into action",example:"We need to implement the new system by January.",korean:"실행하다, 이행하다",level:1},
{id:38,word:"initiative",pos:"n",definition:"a new plan or process introduced to achieve a goal",example:"This is a cost-cutting initiative from leadership.",korean:"계획, 주도권",level:1},
{id:39,word:"invoice",pos:"n",definition:"a document requesting payment for goods or services",example:"Please send the invoice to our accounts team.",korean:"청구서",level:1},
{id:40,word:"launch",pos:"v",definition:"to introduce a new product or project to the public",example:"We will launch the new platform in Q2.",korean:"출시하다",level:1},
{id:41,word:"manage",pos:"v",definition:"to be in charge of people or processes",example:"She will manage the entire product team.",korean:"관리하다",level:1},
{id:42,word:"negotiate",pos:"v",definition:"to discuss terms in order to reach an agreement",example:"We need to negotiate better payment terms.",korean:"협상하다",level:1},
{id:43,word:"objective",pos:"n",definition:"a specific goal to be achieved within a timeframe",example:"Define a measurable objective for each team.",korean:"목표, 과제",level:1},
{id:44,word:"operate",pos:"v",definition:"to run or control a business or system",example:"The company will operate in twenty countries.",korean:"운영하다",level:1},
{id:45,word:"opportunity",pos:"n",definition:"a favorable situation that may lead to success",example:"This is a major business opportunity for us.",korean:"기회",level:1},
{id:46,word:"outsource",pos:"v",definition:"to arrange for work to be done by an outside company",example:"We decided to outsource our customer support.",korean:"외주화하다",level:1},
{id:47,word:"perform",pos:"v",definition:"to carry out or accomplish a task or function",example:"Every team member must perform at their best.",korean:"수행하다, 실적을 내다",level:1},
{id:48,word:"present",pos:"v",definition:"to formally show or explain something to an audience",example:"She will present the findings at Friday's meeting.",korean:"발표하다",level:1},
{id:49,word:"profit",pos:"n",definition:"money gained after subtracting all costs",example:"Net profit exceeded our projections last quarter.",korean:"이익, 수익",level:1},
{id:50,word:"promote",pos:"v",definition:"to raise to a higher position; to advertise",example:"She was promoted to regional director.",korean:"승진시키다, 홍보하다",level:1},
{id:51,word:"proposal",pos:"n",definition:"a formal plan or suggestion put forward for consideration",example:"Please submit your proposal by next Friday.",korean:"제안서",level:1},
{id:52,word:"purchase",pos:"v",definition:"to buy something, especially for business purposes",example:"We plan to purchase new servers this year.",korean:"구매하다",level:1},
{id:53,word:"recommend",pos:"v",definition:"to suggest something as suitable or beneficial",example:"I recommend we revise the current strategy.",korean:"추천하다, 권고하다",level:1},
{id:54,word:"reduce",pos:"v",definition:"to make something smaller in size, amount, or degree",example:"We must reduce overhead costs this fiscal year.",korean:"줄이다, 감소시키다",level:1},
{id:55,word:"report",pos:"v",definition:"to formally communicate information to someone",example:"Please report any issues to your line manager.",korean:"보고하다",level:1},
{id:56,word:"require",pos:"v",definition:"to need something as a necessary condition",example:"This role will require strong leadership skills.",korean:"요구하다",level:1},
{id:57,word:"resolve",pos:"v",definition:"to find a satisfactory solution to a problem",example:"We need to resolve this dispute before it escalates.",korean:"해결하다",level:1},
{id:58,word:"revenue",pos:"n",definition:"the income generated by a business",example:"Revenue grew by fifteen percent last quarter.",korean:"수익, 매출",level:1},
{id:59,word:"review",pos:"v",definition:"to formally examine or assess something",example:"Please review the contract before signing.",korean:"검토하다",level:1},
{id:60,word:"schedule",pos:"v",definition:"to plan something to happen at a specific time",example:"Can we schedule a call for Thursday morning?",korean:"일정을 잡다",level:1},
{id:61,word:"strategy",pos:"n",definition:"a long-term plan to achieve a major goal",example:"Our strategy focuses on digital transformation.",korean:"전략",level:1},
{id:62,word:"submit",pos:"v",definition:"to hand in something for review or consideration",example:"Please submit the report before the deadline.",korean:"제출하다",level:1},
{id:63,word:"support",pos:"v",definition:"to give assistance or backing to someone or something",example:"The IT team will support the system migration.",korean:"지원하다",level:1},
{id:64,word:"target",pos:"n",definition:"a specific result or level of performance to aim for",example:"Our target is to double revenue by next year.",korean:"목표, 타겟",level:1},
{id:65,word:"update",pos:"v",definition:"to make something more current or add new information",example:"Please update the project tracker daily.",korean:"업데이트하다",level:1},
{id:66,word:"vendor",pos:"n",definition:"a company or person that supplies goods or services",example:"We are reviewing proposals from several vendor options.",korean:"공급업체",level:1},
{id:67,word:"verify",pos:"v",definition:"to confirm that something is accurate or true",example:"Always verify the data before presenting results.",korean:"확인하다, 검증하다",level:1},
{id:68,word:"achieve",pos:"v",definition:"to successfully reach a desired outcome through effort",example:"We must achieve our annual sales target.",korean:"달성하다, 성취하다",level:1},
{id:69,word:"assign",pos:"v",definition:"to give a role or task to a specific person",example:"Assign each task clearly with a due date.",korean:"배정하다, 할당하다",level:1},
{id:70,word:"challenge",pos:"n",definition:"a difficult task or situation that tests ability",example:"Our biggest challenge is talent retention.",korean:"도전 과제",level:1},
{id:71,word:"maintain",pos:"v",definition:"to keep something in good condition or working order",example:"We need to maintain open communication at all times.",korean:"유지하다",level:1},
{id:72,word:"partner",pos:"v",definition:"to work together with another organization",example:"We aim to partner with local firms overseas.",korean:"협력하다, 파트너십을 맺다",level:1},
{id:73,word:"process",pos:"n",definition:"a series of actions taken to achieve an outcome",example:"We need to improve our onboarding process.",korean:"절차, 프로세스",level:1},
{id:74,word:"retain",pos:"v",definition:"to keep and not lose something valuable",example:"The biggest challenge is to retain top talent.",korean:"유지하다, 보유하다",level:1},
{id:75,word:"scale",pos:"v",definition:"to increase something proportionally",example:"We need to scale operations quickly to meet demand.",korean:"확장하다, 규모를 키우다",level:1},
{id:76,word:"streamline",pos:"v",definition:"to make a process simpler and more efficient",example:"We plan to streamline the approval process.",korean:"간소화하다",level:1},
{id:77,word:"monitor",pos:"v",definition:"to observe and check progress over time",example:"We will monitor performance on a weekly basis.",korean:"모니터링하다, 감시하다",level:1},
{id:78,word:"optimize",pos:"v",definition:"to make something as effective as possible",example:"We should optimize our supply chain now.",korean:"최적화하다",level:1},
{id:79,word:"integrate",pos:"v",definition:"to combine things so they work together as one",example:"We need to integrate the two platforms.",korean:"통합하다",level:1},
{id:80,word:"sustainable",pos:"adj",definition:"able to be maintained over the long term",example:"We are committed to sustainable business growth.",korean:"지속 가능한",level:1},
{id:81,word:"network",pos:"v",definition:"to meet and build professional relationships",example:"Attend the conference and network with peers.",korean:"네트워킹하다",level:1},
{id:82,word:"compete",pos:"v",definition:"to strive to outperform others in the same market",example:"We need to compete on both price and quality.",korean:"경쟁하다",level:1},
{id:83,word:"adjust",pos:"v",definition:"to modify something slightly to make it more suitable",example:"We need to adjust our pricing strategy.",korean:"조정하다",level:1},
{id:84,word:"market",pos:"v",definition:"to promote and advertise a product or service",example:"We need to market the product to a younger audience.",korean:"마케팅하다, 홍보하다",level:1},
{id:85,word:"workload",pos:"n",definition:"the amount of work one has to do",example:"The workload has increased this quarter.",korean:"업무량",level:1},
{id:86,word:"profit",pos:"n",definition:"financial gain after deducting all costs",example:"We need to increase profit margins next year.",korean:"이익",level:1},
{id:87,word:"benchmark",pos:"v",definition:"to compare against a standard or best practice",example:"We need to benchmark our performance against competitors.",korean:"기준과 비교하다",level:1},
{id:88,word:"capacity",pos:"n",definition:"the maximum amount that can be produced or handled",example:"The factory is running at full capacity.",korean:"역량, 수용력",level:1},
{id:89,word:"distribute",pos:"v",definition:"to give or send something out to several people",example:"Please distribute the meeting notes to all attendees.",korean:"배포하다",level:1},
{id:90,word:"priority",pos:"n",definition:"something dealt with before other things",example:"Customer satisfaction is our top priority.",korean:"우선순위",level:1},
{id:91,word:"resource",pos:"n",definition:"a supply that can be used to accomplish something",example:"We must use our resource wisely.",korean:"자원",level:1},
{id:92,word:"cost",pos:"n",definition:"the amount required to produce or acquire something",example:"We need to reduce the cost of production.",korean:"비용",level:1},
{id:93,word:"lead",pos:"v",definition:"to be in charge of a group or project",example:"She will lead the international expansion team.",korean:"이끌다",level:1},
{id:94,word:"plan",pos:"v",definition:"to decide in advance what you intend to do",example:"We need to plan the rollout carefully.",korean:"계획하다",level:1},
{id:95,word:"sign",pos:"v",definition:"to write your signature on a document",example:"Both parties must sign the agreement.",korean:"서명하다",level:1},
{id:96,word:"solution",pos:"n",definition:"a means of solving a problem",example:"We need a cost-effective solution.",korean:"해결책",level:1},
{id:97,word:"task",pos:"n",definition:"a piece of work to be done",example:"Break the project into smaller task items.",korean:"업무, 과제",level:1},
{id:98,word:"trend",pos:"n",definition:"a general direction in which something is changing",example:"We must adapt to the trend quickly.",korean:"트렌드, 추세",level:1},
{id:99,word:"quality",pos:"n",definition:"the standard of excellence of a product or service",example:"We never compromise on quality.",korean:"품질",level:1},
{id:100,word:"restructure",pos:"v",definition:"to reorganize to improve effectiveness",example:"The company plans to restructure its sales division.",korean:"구조 조정하다",level:1},
// Level 2 - Professional Business
{id:101,word:"accelerate",pos:"v",definition:"to make a process happen faster",example:"We need to accelerate the product launch timeline.",korean:"가속화하다",level:2},
{id:102,word:"accountability",pos:"n",definition:"the obligation to report on and justify one's actions",example:"Accountability is essential in high-performing teams.",korean:"책임감",level:2},
{id:103,word:"acquisition",pos:"n",definition:"the act of gaining ownership of a company or asset",example:"The acquisition will close by the end of Q4.",korean:"인수",level:2},
{id:104,word:"align",pos:"v",definition:"to bring things into agreement or coordination",example:"We need to align our goals with company strategy.",korean:"조율하다, 일치시키다",level:2},
{id:105,word:"authorize",pos:"v",definition:"to give official permission for something",example:"Only the CFO can authorize this level of spend.",korean:"승인하다, 권한을 부여하다",level:2},
{id:106,word:"capital",pos:"n",definition:"money used to fund a business or investment",example:"We need to raise additional capital to grow.",korean:"자본",level:2},
{id:107,word:"circulate",pos:"v",definition:"to send something around to a group of people",example:"Please circulate the minutes to all attendees.",korean:"회람하다, 배포하다",level:2},
{id:108,word:"cohesive",pos:"adj",definition:"united and working well together",example:"We need to build a cohesive team culture.",korean:"결집된, 단합된",level:2},
{id:109,word:"compliance",pos:"n",definition:"acting in accordance with laws or regulations",example:"Full compliance with GDPR is required.",korean:"준수, 컴플라이언스",level:2},
{id:110,word:"concise",pos:"adj",definition:"giving information clearly and in few words",example:"Keep your executive summary concise.",korean:"간결한",level:2},
{id:111,word:"consolidate",pos:"v",definition:"to combine things into a single, stronger whole",example:"We plan to consolidate our three offices into one.",korean:"통합하다, 강화하다",level:2},
{id:112,word:"contingency",pos:"n",definition:"a plan or provision for an unexpected event",example:"Always prepare a contingency plan for key risks.",korean:"비상 계획, 만일의 경우",level:2},
{id:113,word:"convene",pos:"v",definition:"to call people together for a formal meeting",example:"We need to convene an emergency board meeting.",korean:"소집하다",level:2},
{id:114,word:"corporate",pos:"adj",definition:"relating to a large company or corporation",example:"This must align with our corporate values.",korean:"기업의, 법인의",level:2},
{id:115,word:"credibility",pos:"n",definition:"the quality of being trusted and believed",example:"Your credibility is your most important business asset.",korean:"신뢰성",level:2},
{id:116,word:"cultivate",pos:"v",definition:"to develop or nurture something over time",example:"We need to cultivate strong client relationships.",korean:"육성하다, 계발하다",level:2},
{id:117,word:"decisive",pos:"adj",definition:"able to make decisions quickly and clearly",example:"A good leader must be decisive under pressure.",korean:"결단력 있는",level:2},
{id:118,word:"deficit",pos:"n",definition:"the amount by which spending exceeds income",example:"The department is operating at a deficit.",korean:"적자, 부족분",level:2},
{id:119,word:"deploy",pos:"v",definition:"to put resources or technology into use",example:"We will deploy the new software next Monday.",korean:"배치하다, 배포하다",level:2},
{id:120,word:"differentiate",pos:"v",definition:"to make something distinct from competitors",example:"How do we differentiate our product in this market?",korean:"차별화하다",level:2},
{id:121,word:"diversify",pos:"v",definition:"to expand into different areas to reduce risk",example:"We need to diversify our revenue streams.",korean:"다각화하다",level:2},
{id:122,word:"downsize",pos:"v",definition:"to reduce the size of a company or workforce",example:"The firm may need to downsize after the merger.",korean:"규모를 축소하다",level:2},
{id:123,word:"empower",pos:"v",definition:"to give someone the authority or confidence to act",example:"We need to empower employees to make decisions.",korean:"권한을 부여하다",level:2},
{id:124,word:"execute",pos:"v",definition:"to carry out or put a plan into action",example:"We need to execute the strategy flawlessly.",korean:"실행하다",level:2},
{id:125,word:"feasible",pos:"adj",definition:"possible or practical to achieve",example:"Is the proposed timeline feasible for the team?",korean:"실행 가능한",level:2},
{id:126,word:"fiscal",pos:"adj",definition:"relating to government or corporate finances",example:"The fiscal year ends on the thirty-first of December.",korean:"회계의, 재정의",level:2},
{id:127,word:"framework",pos:"n",definition:"a structure or system used to organize activities",example:"We need a clear framework for decision-making.",korean:"체계, 프레임워크",level:2},
{id:128,word:"incentive",pos:"n",definition:"something that motivates or encourages action",example:"Offer a performance incentive to top employees.",korean:"인센티브, 동기",level:2},
{id:129,word:"incorporate",pos:"v",definition:"to include something as part of a larger whole",example:"Please incorporate the feedback into the next draft.",korean:"통합하다, 포함하다",level:2},
{id:130,word:"insight",pos:"n",definition:"a deep understanding of a complex situation",example:"Customer insight drives better product decisions.",korean:"통찰력, 인사이트",level:2},
{id:131,word:"interim",pos:"adj",definition:"intended to last for only a limited period",example:"She has been appointed as interim CEO.",korean:"임시의",level:2},
{id:132,word:"leverage",pos:"v",definition:"to use something to maximum advantage",example:"We can leverage our network to find new clients.",korean:"활용하다",level:2},
{id:133,word:"liability",pos:"n",definition:"something that a company owes or is responsible for",example:"This clause may create a serious legal liability.",korean:"부채, 책임",level:2},
{id:134,word:"mandate",pos:"v",definition:"to officially require or authorize something",example:"The board will mandate quarterly reviews.",korean:"의무화하다, 위임하다",level:2},
{id:135,word:"merger",pos:"n",definition:"the combining of two companies into one",example:"The merger created the largest firm in the sector.",korean:"합병",level:2},
{id:136,word:"milestone",pos:"n",definition:"an important event or stage in a project",example:"We reached a key milestone ahead of schedule.",korean:"이정표, 중요한 단계",level:2},
{id:137,word:"mitigate",pos:"v",definition:"to reduce the severity of a risk or problem",example:"We must mitigate supply chain risks.",korean:"완화하다, 경감하다",level:2},
{id:138,word:"momentum",pos:"n",definition:"the driving force behind a growing trend",example:"We are building strong momentum in the market.",korean:"추진력",level:2},
{id:139,word:"overhead",pos:"n",definition:"regular fixed costs of running a business",example:"We must find ways to cut overhead.",korean:"간접비",level:2},
{id:140,word:"pipeline",pos:"n",definition:"the projects or deals currently in progress",example:"We have a strong sales pipeline for Q3.",korean:"파이프라인, 진행 건",level:2},
{id:141,word:"pivot",pos:"v",definition:"to change direction in a business strategy",example:"We had to pivot our entire business model.",korean:"방향을 전환하다",level:2},
{id:142,word:"procurement",pos:"n",definition:"the process of obtaining goods or services",example:"The procurement team handles all supplier contracts.",korean:"조달",level:2},
{id:143,word:"productivity",pos:"n",definition:"the efficiency with which work is completed",example:"Flexible hours can improve overall productivity.",korean:"생산성",level:2},
{id:144,word:"profitability",pos:"n",definition:"the ability to generate more income than costs",example:"Improving profitability is the board's top priority.",korean:"수익성",level:2},
{id:145,word:"projection",pos:"n",definition:"an estimate or forecast of future performance",example:"Our sales projection looks very optimistic.",korean:"예상, 예측",level:2},
{id:146,word:"proactive",pos:"adj",definition:"taking action to prevent problems before they occur",example:"We need to be proactive about managing risk.",korean:"선제적인, 능동적인",level:2},
{id:147,word:"quarterly",pos:"adv",definition:"once every three months",example:"Revenue is reported quarterly to shareholders.",korean:"분기별로",level:2},
{id:148,word:"redundant",pos:"adj",definition:"no longer needed; made jobless due to restructuring",example:"Several roles became redundant after the merger.",korean:"잉여의, 중복의",level:2},
{id:149,word:"reinforce",pos:"v",definition:"to strengthen something with support or evidence",example:"This data should reinforce our key message.",korean:"강화하다",level:2},
{id:150,word:"scalable",pos:"adj",definition:"able to grow or expand without losing quality",example:"Build a scalable business model from day one.",korean:"확장 가능한",level:2},
{id:151,word:"scope",pos:"n",definition:"the range or extent of a project or activity",example:"We need to clearly define the scope of work.",korean:"범위",level:2},
{id:152,word:"seamless",pos:"adj",definition:"smooth and without interruption",example:"We need to ensure a seamless customer experience.",korean:"매끄러운, 원활한",level:2},
{id:153,word:"shareholder",pos:"n",definition:"a person or company that owns shares in a business",example:"The shareholder meeting is on the fifteenth.",korean:"주주",level:2},
{id:154,word:"shortfall",pos:"n",definition:"a deficit or amount less than what is needed",example:"We have a budget shortfall of fifty thousand dollars.",korean:"부족분, 적자",level:2},
{id:155,word:"subsidiary",pos:"n",definition:"a company controlled by a larger parent company",example:"This is a wholly owned subsidiary of the group.",korean:"자회사",level:2},
{id:156,word:"synergy",pos:"n",definition:"the benefit from combining two things together",example:"The merger created significant operational synergy.",korean:"시너지",level:2},
{id:157,word:"transparency",pos:"n",definition:"openness and clear communication in business",example:"Transparency builds trust with all stakeholders.",korean:"투명성",level:2},
{id:158,word:"turnover",pos:"n",definition:"total sales; or the rate at which employees leave",example:"High employee turnover is very costly.",korean:"매출액, 이직률",level:2},
{id:159,word:"validate",pos:"v",definition:"to prove that something is accurate or sound",example:"We must validate all data before the presentation.",korean:"검증하다",level:2},
{id:160,word:"viable",pos:"adj",definition:"capable of working successfully",example:"Is this a financially viable option for us?",korean:"실행 가능한",level:2},
{id:161,word:"workforce",pos:"n",definition:"all the people employed by an organization",example:"We are investing in our workforce this year.",korean:"인력, 직원",level:2},
{id:162,word:"yield",pos:"v",definition:"to produce a result or financial return",example:"This investment should yield strong returns.",korean:"수익을 내다, 생산하다",level:2},
{id:163,word:"stakeholder",pos:"n",definition:"anyone with an interest in the outcome of a project",example:"Engage each stakeholder early in the process.",korean:"이해관계자",level:2},
{id:164,word:"consensus",pos:"n",definition:"general agreement among a group",example:"We need to reach a consensus before we proceed.",korean:"합의, 컨센서스",level:2},
{id:165,word:"counterpart",pos:"n",definition:"a person who holds the same position in another org",example:"She met her counterpart at the global summit.",korean:"상대방, 대응 인물",level:2},
{id:166,word:"portfolio",pos:"n",definition:"a range of products, investments, or projects",example:"Diversify your portfolio to reduce risk.",korean:"포트폴리오",level:2},
{id:167,word:"prototype",pos:"n",definition:"an early sample built to test a concept",example:"The prototype will be ready for testing next week.",korean:"프로토타입",level:2},
{id:168,word:"receivable",pos:"n",definition:"money owed to a company by its customers",example:"Our accounts receivable has grown significantly.",korean:"미수금, 받을 어음",level:2},
{id:169,word:"refine",pos:"v",definition:"to improve something by making small adjustments",example:"We need to refine our sales pitch.",korean:"다듬다, 개선하다",level:2},
{id:170,word:"rigorous",pos:"adj",definition:"extremely thorough and careful",example:"Apply rigorous standards to all quality checks.",korean:"엄격한, 철저한",level:2},
{id:171,word:"sector",pos:"n",definition:"a distinct part of an economy or industry",example:"We are the leader in the fintech sector.",korean:"분야, 부문",level:2},
{id:172,word:"sustainable",pos:"adj",definition:"able to be continued without negative long-term effects",example:"We want sustainable growth, not just short-term gains.",korean:"지속 가능한",level:2},
{id:173,word:"projection",pos:"n",definition:"a forecast of future figures or trends",example:"Revise the projection based on this quarter's data.",korean:"예상, 예측",level:2},
{id:174,word:"volatility",pos:"n",definition:"the tendency to change rapidly and unpredictably",example:"Market volatility has increased significantly.",korean:"변동성, 불안정성",level:2},
{id:175,word:"benchmark",pos:"n",definition:"a reference point for evaluating performance",example:"This result sets a new industry benchmark.",korean:"기준, 기준치",level:2},
{id:176,word:"proactive",pos:"adj",definition:"anticipating and dealing with problems before they arise",example:"A proactive approach saves time and resources.",korean:"선제적인",level:2},
{id:177,word:"overhead",pos:"n",definition:"ongoing fixed costs not directly tied to production",example:"Reduce overhead to improve your profit margin.",korean:"간접비",level:2},
{id:178,word:"stakeholder",pos:"n",definition:"a party with an interest in an organization",example:"We need buy-in from every stakeholder.",korean:"이해관계자",level:2},
{id:179,word:"agenda",pos:"n",definition:"a schedule of items for discussion",example:"Add this topic to the agenda for next week.",korean:"의제, 안건",level:2},
{id:180,word:"comply",pos:"v",definition:"to follow rules, instructions, or policies",example:"All vendors must comply with our code of conduct.",korean:"준수하다",level:2},
{id:181,word:"benchmark",pos:"n",definition:"a standard used for comparison",example:"Set a benchmark before you start the campaign.",korean:"기준, 벤치마크",level:2},
{id:182,word:"insight",pos:"n",definition:"a valuable understanding of a situation",example:"Market insight helps us make smarter decisions.",korean:"통찰력",level:2},
{id:183,word:"scalable",pos:"adj",definition:"designed to handle growth effectively",example:"The platform must be scalable from the start.",korean:"확장 가능한",level:2},
{id:184,word:"contingency",pos:"n",definition:"a backup plan for unexpected events",example:"We always have a contingency budget set aside.",korean:"비상 계획",level:2},
{id:185,word:"overhead",pos:"n",definition:"the fixed costs of running a business",example:"Reducing overhead is the key to higher margins.",korean:"간접비",level:2},
{id:186,word:"feasible",pos:"adj",definition:"able to be done or achieved",example:"Let us assess whether the plan is feasible.",korean:"실행 가능한",level:2},
{id:187,word:"empower",pos:"v",definition:"to give someone the authority or ability to act",example:"We want to empower our managers to make faster decisions.",korean:"권한을 부여하다",level:2},
{id:188,word:"comply",pos:"v",definition:"to act in line with requirements",example:"Every team must comply with the new data policy.",korean:"준수하다",level:2},
{id:189,word:"momentum",pos:"n",definition:"continuous progress that is gaining speed",example:"We need to maintain our momentum throughout Q4.",korean:"추진력, 모멘텀",level:2},
{id:190,word:"turnover",pos:"n",definition:"annual sales revenue of a business",example:"Our annual turnover increased by thirty percent.",korean:"매출액",level:2},
{id:191,word:"merger",pos:"n",definition:"a union of two organizations",example:"Shareholders approved the merger last week.",korean:"합병",level:2},
{id:192,word:"viable",pos:"adj",definition:"practical and likely to work",example:"We need to present a viable alternative.",korean:"실행 가능한",level:2},
{id:193,word:"leverage",pos:"n",definition:"the power to influence a situation",example:"We have significant leverage in this negotiation.",korean:"영향력, 레버리지",level:2},
{id:194,word:"synergy",pos:"n",definition:"increased effectiveness from working together",example:"We expect strong synergy between the two brands.",korean:"시너지",level:2},
{id:195,word:"execute",pos:"v",definition:"to perform or carry out a task or plan",example:"The key is to execute the plan on time.",korean:"실행하다",level:2},
{id:196,word:"deploy",pos:"v",definition:"to put into use strategically",example:"When will we deploy the new CRM system?",korean:"배치하다, 배포하다",level:2},
{id:197,word:"shortfall",pos:"n",definition:"a gap between what is needed and what is available",example:"There is a shortfall in this month's revenue.",korean:"부족분",level:2},
{id:198,word:"credibility",pos:"n",definition:"the quality of being convincing and trustworthy",example:"Publishing case studies boosts our credibility.",korean:"신뢰성",level:2},
{id:199,word:"cohesive",pos:"adj",definition:"unified and acting as one",example:"A cohesive brand message is crucial.",korean:"일관된, 단합된",level:2},
{id:200,word:"transparency",pos:"n",definition:"open communication and honest reporting",example:"Investors demand full transparency in reporting.",korean:"투명성",level:2},
// Level 3 - Advanced Business
{id:201,word:"acumen",pos:"n",definition:"keen insight and practical business judgment",example:"Her business acumen helped close many major deals.",korean:"통찰력, 예리함",level:3},
{id:202,word:"adjudicate",pos:"v",definition:"to make a formal judgment on a disputed matter",example:"An independent panel will adjudicate the dispute.",korean:"판결하다, 중재하다",level:3},
{id:203,word:"aggregate",pos:"v",definition:"to collect and combine data from multiple sources",example:"Please aggregate all figures before the board meeting.",korean:"집계하다, 취합하다",level:3},
{id:204,word:"arbitration",pos:"n",definition:"a method of resolving disputes outside of court",example:"The contract dispute went to arbitration.",korean:"중재",level:3},
{id:205,word:"articulate",pos:"v",definition:"to express ideas clearly and fluently",example:"Please articulate your value proposition more clearly.",korean:"명확히 표현하다",level:3},
{id:206,word:"attrition",pos:"n",definition:"reduction in workforce through voluntary departures",example:"Reducing attrition is our top HR priority.",korean:"자연 감소, 이탈",level:3},
{id:207,word:"autonomy",pos:"n",definition:"the right to make one's own decisions",example:"Give teams more autonomy to innovate.",korean:"자율성",level:3},
{id:208,word:"capitalization",pos:"n",definition:"the total market value of a company's shares",example:"The firm's market capitalization doubled in one year.",korean:"시가 총액",level:3},
{id:209,word:"caveat",pos:"n",definition:"a warning or qualification added to a statement",example:"There is one important caveat to this agreement.",korean:"단서, 경고",level:3},
{id:210,word:"churn",pos:"n",definition:"the rate at which customers stop using a service",example:"Reducing customer churn is critical for growth.",korean:"이탈률",level:3},
{id:211,word:"commoditize",pos:"v",definition:"to turn into a widely available generic product",example:"If we don't innovate, our product will commoditize.",korean:"상품화하다",level:3},
{id:212,word:"compel",pos:"v",definition:"to force or strongly motivate someone to do something",example:"The data should compel the board to act now.",korean:"강요하다, 촉구하다",level:3},
{id:213,word:"contingent",pos:"adj",definition:"depending on specific conditions being met",example:"The bonus is contingent on reaching the annual target.",korean:"조건부의, 상황에 따른",level:3},
{id:214,word:"contractual",pos:"adj",definition:"relating to a contract or agreed obligations",example:"Both parties must fulfill their contractual duties.",korean:"계약상의",level:3},
{id:215,word:"copious",pos:"adj",definition:"abundant; more than enough",example:"She took copious notes during the board presentation.",korean:"풍부한, 많은",level:3},
{id:216,word:"cross-functional",pos:"adj",definition:"involving people from different departments",example:"This requires strong cross-functional collaboration.",korean:"부서 간의",level:3},
{id:217,word:"default",pos:"n",definition:"failure to meet a financial obligation",example:"The borrower was at risk of default.",korean:"채무 불이행",level:3},
{id:218,word:"deliverable",pos:"n",definition:"a product or result that must be provided",example:"List every deliverable and its due date in the brief.",korean:"산출물, 납품물",level:3},
{id:219,word:"depreciation",pos:"n",definition:"reduction in the value of an asset over time",example:"Depreciation reduces the asset value on the balance sheet.",korean:"감가상각",level:3},
{id:220,word:"differentiation",pos:"n",definition:"making a product or service distinct from competitors",example:"Product differentiation is the core of our strategy.",korean:"차별화",level:3},
{id:221,word:"dilute",pos:"v",definition:"to weaken or reduce the value of something",example:"Issuing new shares will dilute existing ownership.",korean:"희석하다",level:3},
{id:222,word:"disruptive",pos:"adj",definition:"causing major changes to an industry or market",example:"This is a disruptive technology in financial services.",korean:"파괴적인, 혁신적인",level:3},
{id:223,word:"divest",pos:"v",definition:"to sell off a business unit or assets",example:"We plan to divest our underperforming subsidiaries.",korean:"매각하다",level:3},
{id:224,word:"due diligence",pos:"n",definition:"thorough investigation before a business decision",example:"Always conduct full due diligence before any acquisition.",korean:"실사",level:3},
{id:225,word:"ecosystem",pos:"n",definition:"a network of interconnected businesses or users",example:"We are building a broad fintech ecosystem.",korean:"생태계",level:3},
{id:226,word:"embargo",pos:"n",definition:"an official ban on trade with a country",example:"An embargo was placed on the shipment.",korean:"금수 조치",level:3},
{id:227,word:"endorse",pos:"v",definition:"to publicly declare support for something",example:"The CEO will personally endorse this initiative.",korean:"지지하다, 보증하다",level:3},
{id:228,word:"equity",pos:"n",definition:"ownership interest in a company after liabilities",example:"Equity investors share in the company's upside.",korean:"자본, 지분",level:3},
{id:229,word:"escalate",pos:"v",definition:"to raise an issue to a higher authority",example:"Escalate unresolved issues to your line manager.",korean:"에스컬레이션하다, 확대하다",level:3},
{id:230,word:"expedite",pos:"v",definition:"to speed up a process or action",example:"Please expedite the contract approval process.",korean:"신속히 처리하다",level:3},
{id:231,word:"explicit",pos:"adj",definition:"clearly stated and leaving no room for doubt",example:"Set explicit expectations from the very first meeting.",korean:"명시적인",level:3},
{id:232,word:"fiduciary",pos:"adj",definition:"relating to a duty of trust on behalf of others",example:"Directors have a fiduciary duty to shareholders.",korean:"수탁자의, 신임의",level:3},
{id:233,word:"flagship",pos:"adj",definition:"the most important or best product in a range",example:"This is our flagship product for the enterprise market.",korean:"주력의",level:3},
{id:234,word:"governance",pos:"n",definition:"the system by which a company is controlled",example:"Good corporate governance builds long-term investor trust.",korean:"지배 구조",level:3},
{id:235,word:"granular",pos:"adj",definition:"detailed at a very fine level",example:"We need more granular data on user behavior.",korean:"세분화된, 상세한",level:3},
{id:236,word:"hedge",pos:"v",definition:"to protect against financial risk",example:"We need to hedge our exposure to currency fluctuation.",korean:"위험을 회피하다",level:3},
{id:237,word:"hierarchy",pos:"n",definition:"a system organized by rank or authority",example:"Flatten the hierarchy to speed up decision-making.",korean:"계층 구조",level:3},
{id:238,word:"holistic",pos:"adj",definition:"considering all parts as a whole system",example:"Take a holistic view when assessing business performance.",korean:"전체론적인",level:3},
{id:239,word:"incentivize",pos:"v",definition:"to offer rewards to motivate desired behavior",example:"Use bonuses to incentivize top sales performance.",korean:"인센티브를 제공하다",level:3},
{id:240,word:"incumbent",pos:"adj",definition:"currently holding a particular position or role",example:"The incumbent CEO will retire at the end of the year.",korean:"현직의",level:3},
{id:241,word:"indemnify",pos:"v",definition:"to compensate for loss or to protect from liability",example:"The contract includes a clause to indemnify the vendor.",korean:"배상하다",level:3},
{id:242,word:"intangible",pos:"adj",definition:"not physical; unable to be touched or measured easily",example:"Brand reputation is a key intangible asset.",korean:"무형의",level:3},
{id:243,word:"iterate",pos:"v",definition:"to repeat a process in order to improve results",example:"We iterate quickly based on real user feedback.",korean:"반복하다, 개선하다",level:3},
{id:244,word:"jeopardize",pos:"v",definition:"to put something at risk of harm or loss",example:"A delay could jeopardize the entire deal.",korean:"위태롭게 하다",level:3},
{id:245,word:"liquidate",pos:"v",definition:"to sell assets to pay off debts",example:"The company was forced to liquidate its holdings.",korean:"청산하다",level:3},
{id:246,word:"lucrative",pos:"adj",definition:"producing a large profit",example:"This is a highly lucrative contract for us.",korean:"수익성 있는",level:3},
{id:247,word:"mandate",pos:"n",definition:"an official instruction or authorization",example:"We have a clear mandate from the board to cut costs.",korean:"위임, 명령",level:3},
{id:248,word:"meticulous",pos:"adj",definition:"very careful and precise about details",example:"She is meticulous in her financial reporting.",korean:"꼼꼼한, 세심한",level:3},
{id:249,word:"monetize",pos:"v",definition:"to convert something into a source of income",example:"We need to monetize our user base effectively.",korean:"수익화하다",level:3},
{id:250,word:"niche",pos:"n",definition:"a specialized segment of the market",example:"We serve a very specific niche in the B2B market.",korean:"틈새 시장",level:3},
{id:251,word:"onboard",pos:"v",definition:"to integrate a new employee or client into the system",example:"We need to onboard the new hires by next Monday.",korean:"온보딩하다",level:3},
{id:252,word:"optimal",pos:"adj",definition:"the best possible under given conditions",example:"Find the optimal balance between speed and quality.",korean:"최적의",level:3},
{id:253,word:"paradigm",pos:"n",definition:"a typical pattern or model; a major shift in thinking",example:"This technology represents a new industry paradigm.",korean:"패러다임",level:3},
{id:254,word:"pragmatic",pos:"adj",definition:"dealing with things realistically and practically",example:"Take a pragmatic approach to contract negotiation.",korean:"실용적인",level:3},
{id:255,word:"preemptive",pos:"adj",definition:"done in order to prevent something before it happens",example:"Take preemptive action before the problem escalates.",korean:"선제적인",level:3},
{id:256,word:"proprietary",pos:"adj",definition:"owned by a company and not to be shared",example:"This is our proprietary technology and trade secret.",korean:"독점적인",level:3},
{id:257,word:"provisional",pos:"adj",definition:"arranged for now but likely to change",example:"This is a provisional agreement pending board approval.",korean:"임시의",level:3},
{id:258,word:"prudent",pos:"adj",definition:"careful and sensible when managing resources",example:"It is prudent to seek legal counsel before signing.",korean:"신중한",level:3},
{id:259,word:"quantify",pos:"v",definition:"to express as a number or measurable amount",example:"Please quantify the financial impact of this decision.",korean:"수치화하다",level:3},
{id:260,word:"reconcile",pos:"v",definition:"to verify that two sets of records agree",example:"Please reconcile the accounts by end of month.",korean:"대사하다, 조정하다",level:3},
{id:261,word:"reputable",pos:"adj",definition:"having a good reputation",example:"We only work with reputable suppliers.",korean:"평판이 좋은",level:3},
{id:262,word:"resilience",pos:"n",definition:"the ability to recover quickly from difficulties",example:"Business resilience is built through planning.",korean:"회복력, 탄력성",level:3},
{id:263,word:"scrutinize",pos:"v",definition:"to examine something very carefully",example:"The auditors will scrutinize every transaction.",korean:"면밀히 조사하다",level:3},
{id:264,word:"solvent",pos:"adj",definition:"able to pay all debts as they come due",example:"The company remains solvent despite the slowdown.",korean:"지불 능력이 있는",level:3},
{id:265,word:"sophisticated",pos:"adj",definition:"highly developed and complex",example:"Our clients expect a sophisticated solution.",korean:"세련된, 정교한",level:3},
{id:266,word:"streamline",pos:"v",definition:"to simplify a process to make it more efficient",example:"We need to streamline procurement to cut costs.",korean:"간소화하다",level:3},
{id:267,word:"subordinate",pos:"n",definition:"a person who is in a lower position in a hierarchy",example:"A manager must support and develop each subordinate.",korean:"부하직원",level:3},
{id:268,word:"transactional",pos:"adj",definition:"involving a commercial exchange or interaction",example:"We want to build relationships, not just transactional deals.",korean:"거래 위주의",level:3},
{id:269,word:"valuation",pos:"n",definition:"an estimate of the value of a business or asset",example:"The startup's valuation reached one billion dollars.",korean:"가치 평가",level:3},
{id:270,word:"workforce",pos:"n",definition:"the people engaged in or available for work",example:"Upskilling the workforce is a strategic priority.",korean:"인력",level:3},
{id:271,word:"arbitrage",pos:"n",definition:"profiting from price differences in different markets",example:"They used regulatory arbitrage to reduce costs.",korean:"차익 거래",level:3},
{id:272,word:"cadence",pos:"n",definition:"the regular rhythm or frequency of a process",example:"We set a weekly cadence for project check-ins.",korean:"리듬, 주기",level:3},
{id:273,word:"collateral",pos:"n",definition:"an asset pledged as security for a loan",example:"The property was used as collateral for the loan.",korean:"담보",level:3},
{id:274,word:"deferral",pos:"n",definition:"the postponement of a payment or recognition",example:"A tax deferral can improve short-term cash flow.",korean:"이연, 연기",level:3},
{id:275,word:"diligence",pos:"n",definition:"careful and persistent work or effort",example:"Professional diligence is expected from every employee.",korean:"성실함, 근면",level:3},
{id:276,word:"incumbent",pos:"n",definition:"the current holder of a position",example:"The incumbent must hand over within thirty days.",korean:"현직자",level:3},
{id:277,word:"insolvent",pos:"adj",definition:"unable to pay debts when they are due",example:"The firm was declared insolvent after the audit.",korean:"지불 불능의",level:3},
{id:278,word:"litigious",pos:"adj",definition:"prone to engaging in lawsuits",example:"Work carefully in this litigious industry.",korean:"소송을 좋아하는",level:3},
{id:279,word:"net margin",pos:"n",definition:"profit as a percentage of total revenue after all costs",example:"Our net margin improved by three points.",korean:"순이익률",level:3},
{id:280,word:"overdue",pos:"adj",definition:"past the expected or required date",example:"The payment is now thirty days overdue.",korean:"기한이 지난",level:3},
{id:281,word:"paradigm shift",pos:"n",definition:"a fundamental change in approach or underlying assumptions",example:"AI represents a paradigm shift in every industry.",korean:"패러다임 전환",level:3},
{id:282,word:"prerequisite",pos:"n",definition:"something required as a prior condition",example:"Board approval is a prerequisite for this investment.",korean:"전제 조건",level:3},
{id:283,word:"procurement",pos:"n",definition:"acquiring goods or services for an organization",example:"All procurement must follow the approved vendor list.",korean:"조달",level:3},
{id:284,word:"rationale",pos:"n",definition:"the reasons or logic behind a decision",example:"Please explain the rationale for this budget increase.",korean:"근거, 이유",level:3},
{id:285,word:"redundancy",pos:"n",definition:"the state of being no longer needed; a layoff",example:"The merger led to widespread redundancy.",korean:"잉여, 해고",level:3},
{id:286,word:"remuneration",pos:"n",definition:"payment or compensation for work done",example:"The remuneration package includes a performance bonus.",korean:"보수, 보상",level:3},
{id:287,word:"repercussion",pos:"n",definition:"an unintended consequence of an action",example:"Consider the legal repercussion before making that statement.",korean:"파급 효과, 결과",level:3},
{id:288,word:"retrenchment",pos:"n",definition:"cutting costs by reducing staff or activities",example:"The economic crisis forced a period of retrenchment.",korean:"긴축, 감원",level:3},
{id:289,word:"ROI",pos:"n",definition:"return on investment; a measure of profitability",example:"What is the expected ROI on this campaign?",korean:"투자 수익률 (ROI)",level:3},
{id:290,word:"sanctioned",pos:"adj",definition:"officially approved or penalized",example:"Only sanctioned vendors are listed on our portal.",korean:"승인된, 제재를 받은",level:3},
{id:291,word:"sensitivity analysis",pos:"n",definition:"a study of how output varies with changes in inputs",example:"Run a sensitivity analysis on key financial assumptions.",korean:"민감도 분석",level:3},
{id:292,word:"stakeholder alignment",pos:"n",definition:"ensuring all parties share the same goals",example:"Stakeholder alignment is critical before launch.",korean:"이해관계자 조율",level:3},
{id:293,word:"succession",pos:"n",definition:"the process of replacing a leader",example:"We need a clear succession plan for senior roles.",korean:"승계",level:3},
{id:294,word:"tangible",pos:"adj",definition:"clear and definite; able to be measured",example:"Provide tangible evidence to support your claims.",korean:"유형의, 실질적인",level:3},
{id:295,word:"traction",pos:"n",definition:"early progress and positive momentum in business",example:"Our product is gaining real traction in the market.",korean:"견인력, 성장세",level:3},
{id:296,word:"turnaround",pos:"n",definition:"a reversal from poor to strong performance",example:"The new CEO led an impressive business turnaround.",korean:"턴어라운드, 회생",level:3},
{id:297,word:"underwrite",pos:"v",definition:"to agree to fund or guarantee something",example:"The bank agreed to underwrite the bond issuance.",korean:"보증하다, 인수하다",level:3},
{id:298,word:"vested interest",pos:"n",definition:"a personal stake in the outcome of a situation",example:"Each party has a vested interest in the deal's success.",korean:"기득권, 이해관계",level:3},
{id:299,word:"write-off",pos:"n",definition:"an asset or debt acknowledged as lost",example:"The bad debt was treated as a write-off.",korean:"대손 처리, 손실 처리",level:3},
{id:300,word:"zero-sum",pos:"adj",definition:"a situation where one party's gain equals another's loss",example:"Negotiation does not have to be a zero-sum game.",korean:"제로섬의",level:3}
];